# Generated by Django 3.1.7 on 2021-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeioEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meio de envio ',
                'verbose_name_plural': 'Meios de envio',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tecnologia ',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento ',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
    ]
