# Generated by Django 3.1.7 on 2021-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('CPNJ', models.CharField(max_length=30, verbose_name='')),
                ('uasg', models.IntegerField(null=True, verbose_name='Número do UASG')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('observacao', models.TextField(null=True, verbose_name='Observações')),
                ('dataCrialcao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
