# Generated by Django 3.1.7 on 2021-04-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidadeLicitacao', models.CharField(choices=[('Carta convite', 'Carta convite'), ('Emergencial', 'Emergencial'), ('Chamada pública', 'Chamada pública'), ('Shopping', 'Shopping'), ('Concorrência', 'Concorrência'), ('Tomada de preços', 'Tomada de preços'), ('Pregão', 'Pregão')], max_length=25, verbose_name='Modalidade da Licitação')),
                ('tipoPregao', models.CharField(choices=[('Presencial', 'Presencial'), ('Eletrônico', 'Eletrônico')], max_length=25, null=True, verbose_name='Tipo de Pregão')),
                ('numLicitacao', models.CharField(max_length=50, null=True, verbose_name='Código da pregão')),
                ('registroPreco', models.BooleanField(verbose_name='Registro de preço?')),
                ('objeto', models.TextField(null=True, verbose_name='Objeto da licitação')),
                ('valorEstimado', models.FloatField(null=True, verbose_name='Valor estimado')),
                ('observacoes', models.TextField(null=True, verbose_name='Observações')),
                ('statusLicitacao', models.CharField(choices=[('Publicada', 'Publicada'), ('Recolhida', 'Recolhida'), ('Republicada', 'Republicada'), ('Encerrada', 'Encerrada')], max_length=11, verbose_name='Situação da Licitação')),
                ('statusInterjato', models.CharField(choices=[('Em analise', 'Em analise'), ('Faltando documentação', 'Faltando documentação'), ('Apta', 'Apta'), ('Conquistada', 'Conquistada'), ('Inapta', 'Inapta')], max_length=50, null=True, verbose_name='Status da Licitação')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('clienteBeneficiadoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteBeneficiadoID', to='clientes.cliente', verbose_name='Cliente Beneficiado')),
                ('clienteGerenciadorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteGerenciadorID', to='clientes.cliente', verbose_name='Cliente Gerenciador')),
                ('tecnologiaId', models.ManyToManyField(to='contrib.Tecnologia', verbose_name='Tecnologias')),
            ],
            options={
                'verbose_name': 'Licitacão',
                'verbose_name_plural': 'Licitações',
            },
        ),
        migrations.CreateModel(
            name='Recolhimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRecolhimento', models.DateField(verbose_name='Data de recolhimento')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Recolhimento',
                'verbose_name_plural': 'Recolhimentos',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPublicacao', models.DateField(verbose_name='Data de publicação')),
                ('dataQuestionamento', models.DateField(verbose_name='Data para questionamento')),
                ('dataImpugnacao', models.DateField(verbose_name='Data para impugnação')),
                ('dataExecucao', models.DateField(verbose_name='Data para Execução')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoLink', models.CharField(choices=[('Questionamentos', 'Questionamentos'), ('Impugnação', 'Impugnação'), ('Anuncios', 'Anuncios'), ('Documentos', 'Documentos')], max_length=50, verbose_name='Tipo do Link')),
                ('link', models.TextField(verbose_name='Link')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300, verbose_name='Comentário')),
                ('documento', models.FileField(upload_to='documentos', verbose_name='Documento')),
                ('dataPublicacao', models.DateField(verbose_name='Data de publicação')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
                ('tipoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.tipo', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do contato')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função do contato')),
                ('telefone', models.CharField(max_length=50, null=True, verbose_name='Telefone do contato')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='E-mail do contato')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('comentario', models.TextField(max_length=200, verbose_name='Comentario')),
                ('documento', models.FileField(null=True, upload_to='documentos', verbose_name='Documento')),
                ('criticidade', models.CharField(choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Media'), (4, 'Informação')], max_length=50, verbose_name='Criticidade')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitacão')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatário')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
                ('meioEnvioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.meioenvio', verbose_name='Meio de envio')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
