# Generated by Django 3.1.7 on 2021-03-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=200, verbose_name='Órgão licitante')),
                ('pregao', models.IntegerField(verbose_name='Número do pregão')),
                ('uasg', models.IntegerField(verbose_name='Número do UASG')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('status', models.CharField(choices=[('Publicada', 'Publicada'), ('Recolhida', 'Recolhida'), ('Republicada', 'Republicada'), ('Encerrada', 'Encerrada')], max_length=11, verbose_name='Situação')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('tecnologiaId', models.ManyToManyField(to='contrib.Tecnologia', verbose_name='Tecnologias')),
            ],
            options={
                'verbose_name': 'Licitacão',
                'verbose_name_plural': 'Licitações',
            },
        ),
        migrations.CreateModel(
            name='Recolhimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRecolhimento', models.DateField(verbose_name='Data de recolhimento')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Recolhimento',
                'verbose_name_plural': 'Recolhimentos',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPublicacao', models.DateField(verbose_name='Data de publicação')),
                ('dataQuestionamento', models.DateField(verbose_name='Data para questionamento')),
                ('dataImpugnacao', models.DateField(verbose_name='Data para impugnação')),
                ('dataExecucao', models.DateField(verbose_name='Data para Execução')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300, verbose_name='Comentário')),
                ('documento', models.FileField(upload_to='documentos', verbose_name='Documento')),
                ('dataPublicacao', models.DateField(verbose_name='Data de publicação')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
                ('tipoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.tipo', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('criticidade', models.CharField(max_length=50, verbose_name='Criticidade')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitacão')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatário')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataEdicao', models.DateField(auto_now=True)),
                ('licitacaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.licitacao', verbose_name='Licitação')),
                ('meioEnvioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.meioenvio', verbose_name='Meio de envio')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
