# Generated by Django 3.1.7 on 2021-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacao',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='uasg',
            field=models.IntegerField(null=True, verbose_name='Número do UASG'),
        ),
    ]
