# Generated by Django 3.1.7 on 2021-03-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('licitacoes', '0002_auto_20210318_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='clienteID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='cliente'),
            preserve_default=False,
        ),
    ]
