# Generated by Django 3.1.7 on 2021-03-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0003_licitacao_clienteid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacao',
            name='orgao',
        ),
        migrations.AddField(
            model_name='licitacao',
            name='valorEstimado',
            field=models.FloatField(null=True, verbose_name='Valor estimado'),
        ),
    ]
